name: tourist_guide
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - images/


  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets_fonts/ElMessiri-Regular.ttf
        - asset: assets_fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets_fonts/ElMessiri-Bold.ttf
          weight: 700

    - family: Amiri
      fonts:
        - asset: assets_fonts/Amiri-Regular.ttf
        - asset: assets_fonts/ElMessiri-Bold.ttf
          weight: 700
